version: '3'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.1"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
      - ./enhancements/hour_range_enhancement.py:/opt/elastalert/elastalert_modules/hour_range_enhancement.py
    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'
    depends_on:
      - elasticsearch

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elastalert

